<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Compositor</AssemblyName>
    <InvariantGlobalization>true</InvariantGlobalization>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <SkiaSharpVersion>2.88.9</SkiaSharpVersion>
    <AvaloniaVersion>11.2.1</AvaloniaVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="SkiaSharp" Version="$(SkiaSharpVersion)" />
  </ItemGroup>

</Project>
